services:
  - type: web # Value is "web" as required
    name: famiory-admin-frontend
    runtime: node # MODIFIED: Use 'runtime' instead of 'env' for a Web Service
    plan: free
    
    # The build command remains the same
    buildCommand: npm ci && npm run build
    
    # MODIFIED: The start command now uses the new 'start' script from package.json
    startCommand: npm run start

    # Environment variables are still configured the same way
    envVars:
      - key: VITE_API_BASE_URL